version: "3.9"

services:
  # === RABBIT MQ BROKER ===
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq_go_net
        
  # === OCELOT API GATEWAY ===
  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:4100
    ports:
      - "4100:4100"
  
  # === TODOS API ===
  todo-db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
  todo-api:
    build:
      context: ./TodoApi
      dockerfile: Dockerfile
    environment:
      - HTTPS_PORT=5001
      - ASPNETCORE_URLS=https://*:443;https://*:5001;http://*:4001
      - ConnectionStrings:DatabaseConnection=Server=todo-db;Database=TodoDatabase;User=sa;Password=1Secure*Password1;
    ports:
      - "5001:5001"
      - "4001:4001"
    depends_on:
      - todo-db
        
  # === TEAMS API ===
  teams-db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
  teams-api:
    build:
      context: ./TeamsApi
      dockerfile: Dockerfile
    environment:
      - HTTPS_PORT=5002
      - ASPNETCORE_URLS=https://*:443;https://*:5002;http://*:4002
      - ConnectionStrings:DatabaseConnection=Server=teams-db;Database=TeamsDatabase;User=sa;Password=1Secure*Password1;
    ports:
      - "5002:5002"
      - "4002:4002"
    depends_on:
      - teams-db
        
networks:
  rabbitmq_go_net:
    driver: bridge