version: "3.9"

services:
  # === RABBIT MQ BROKER ===
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    restart: on-failure
    
  # === SQL DATABASE SERVER ===
  
  sql-server:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    restart: on-failure
  
  # === OCELOT API GATEWAY ===
  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:4100
      - ENABLE_SWAGGER=true
    ports:
      - "4100:4100"
    restart: on-failure
  
  # === TODOS API ===
  todo-api:
    build:
      context: ./TodoApi
      dockerfile: Dockerfile
    environment:
      - HTTPS_PORT=5001
      - ASPNETCORE_URLS=https://*:443;https://*:5001;http://*:4001
      - ConnectionStrings:DatabaseConnection=Server=sql-server;Database=TodoDatabase;User=sa;Password=1Secure*Password1;
      - ENABLE_SWAGGER=true
    ports:
      - "5001:5001"
      - "4001:4001"
    restart: on-failure
    depends_on:
      - sql-server
        
  # === TEAMS API ===
  team-api:
    build:
      context: ./TeamsApi
      dockerfile: Dockerfile
    environment:
      - HTTPS_PORT=5002
      - ASPNETCORE_URLS=https://*:443;https://*:5002;http://*:4002
      - ENABLE_SWAGGER=true
      - ConnectionStrings:DatabaseConnection=Server=sql-server;Database=TeamsDatabase;User=sa;Password=1Secure*Password1;
    ports:
      - "5002:5002"
      - "4002:4002"
    restart: on-failure
    depends_on:
      - sql-server
        
  # === TEAM MEMBERSHIPS API ===
  team-membership-api:
    build:
      context: ./TeamMembershipApi
      dockerfile: Dockerfile
    environment:
      - HTTPS_PORT=5003
      - ASPNETCORE_URLS=https://*:443;https://*:5003;http://*:4003
      - ConnectionStrings:DatabaseConnection=Server=sql-server;Database=TeamMembershipsDatabase;User=sa;Password=1Secure*Password1;
      - ENABLE_SWAGGER=true
    ports:
      - "5003:5003"
      - "4003:4003"
    restart: on-failure
    depends_on:
      - sql-server
  # === USER API ===
  user-api:
    build:
      context: ./UsersApi
      dockerfile: Dockerfile
    environment:
      - HTTPS_PORT=5004
      - ASPNETCORE_URLS=https://*:443;https://*:5004;http://*:4004
      - ConnectionStrings:DatabaseConnection=Server=sql-server;Database=UsersDatabase;User=sa;Password=1Secure*Password1;
      - ENABLE_SWAGGER=true
    ports:
      - "5004:5004"
      - "4004:4004"
    restart: on-failure
    depends_on:
      - sql-server
  # === USER API ===
  authentication-api:
    build:
      context: ./AuthenticationApi
      dockerfile: Dockerfile
    environment:
      - HTTPS_PORT=5005
      - ASPNETCORE_URLS=https://*:443;https://*:5005;http://*:4005
      - ConnectionStrings:DatabaseConnection=Server=sql-server;Database=AccountDatabase;User=sa;Password=1Secure*Password1;
      - ENABLE_SWAGGER=true
      - CORS_ORIGINS=https://localhost:3000
    ports:
      - "5005:5005"
      - "4005:4005"
    restart: on-failure
    depends_on:
      - sql-server