version: "3.9"

services:
  todo-api:
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1